config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about',to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end


# class Stack
#   def initialize(size)
#     @size = size
#     @store = Array.new(@size)
#     @top = -1
#   end
  
#   def pop
#     if empty?
#       nil
#     else
#       popped = @store[@top]
#       @store[@top] = nil
#       @top = @top.pred
#       popped
#     end
#   end
  
#   def push(element)
#     if full? or element.nil?
#       nil
#     else
#       @top = @top.succ
#       @store[@top] = element
#       self
#     end
#   end
  
#   def size
#     @size
#   end
  
#   def look
#     @store[@top]
#   end
  
#   private
  
#   def full?
#     @top == (@size - 1)
#   end
  
#   def empty?
#     @top == -1
#   end
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence:true,length:{minimum: 6,maximum:100}
    validates :description, presence:true,length:{minimum: 10,maximum:300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email=email.downcase}
    has_many :articles, dependent: :destroy
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: {minimum: 3, maximum: 25}
    VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105}, format: { with: VALID_EMAIL}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "you must  be logged in first"
            redirect_to login_path
        end
    end
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_art, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :delete]

    def show
    end

    def index
        @arts=Article.paginate(page: params[:page], per_page: 5)
    end

    def new
        @art=Article.new
    end

    def edit
    end

    def create
        @art=Article.new(art_params)
        @art.user=current_user
        #nd(@art.user_id)
        if @art.save
            flash[:notice] = "Atrical was created successfully."
            redirect_to @art
        else
            render 'new'
        end
        #render plain: @art.inspect
    end

    def update
        if @art.update(art_params)
            flash[:notice] = "Atrical was updated successfully."
            redirect_to @art
        else
            render 'edit'
        end
    end
    
    def destroy
        @art.destroy
        #@art.save
        redirect_to articles_path
    end

    private
    def set_art
        @art=Article.find(params[:id])
    end

    def art_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
        if current_user != @art.user && !current_user.admin?
            flash[:alert] = "you can only edit/delete your articles"
            redirect_to @art
        end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]

    def new
        @category=Category.new
    end

    def index
        @cats=Category.paginate(page: params[:page], per_page: 5)
    end

    def show
        @category=Category.find(params[:id])
        @arts=@category.articles.paginate(page: params[:page], per_page: 5)
    end
    
    def edit
        @category=Category.find(params[:id])
    end

    def update
        @category=Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category was updated successfully."
            redirect_to @category
        else
            render 'edit'
        end    
    end

    def create
        @category=Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else
            render 'new'
        end
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "you are not admin"
            redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        redirect_to articles_path if logged_in?
    end
    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user=User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "logged in successfully"
            redirect_to user
        else
            flash.now[:alert] = "username or password must be wrong"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "logged out"
        redirect_to root_path

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
        @arts=@user.articles.paginate(page: params[:page], per_page: 5)
    end

    def index
        @users=User.paginate(page: params[:page], per_page: 5)
    end

    def new 
        @user=User.new
    end

    def edit 
    end

    def update
        if @user.update(user_params)
            flash[:notice] = "your details was successfully updated"
            redirect_to @user
        else
            render 'edit'
        end

    end

    def create
        @user=User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "welcome #{@user.username},you have successfully signed up"
            redirect_to articles_path
        else
            render 'new'
        end
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "your account and all associated articles successfully deleted"
        redirect_to root_path
    end

    private
    def user_params
        params.require(:user).permit(:username,:email,:password)
    end

    def set_user
        @user=User.find(params[:id])
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "you can edit/delete only your profile"
            redirect_to user_path(@user)
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = {size:80})
        email = user.email.downcase
        hash = Digest::MD5.hexdigest(email)
        size=options[:size]
        url="https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(url,alt:user.username,class:"rounded shadow mx-auto d-block")
    end


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="container">
    <% @arts.each do |a| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center mb-5 bg-white rounded">
                    <div class="card-header font-italic">
                        by <%= link_to a.user.username, user_path(a.user) %>
                        <% if a.categories.any?  %>
                            <div class="mt-2"><%= render a.categories %> </div>
                        <% end %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to a.title,article_path(a),class: "text-success" %></h5>
                        <p class="card-text"><%= truncate(a.description,length:100) %></p>
                        <%= link_to "View",article_path(a),class:"btn btn-outline-success" %>
                        <% if logged_in? && (a.user == current_user || current_user.admin?) %>
                            <%= link_to "Edit",edit_article_path(a),class:"btn btn-outline-info" %>
                            <%= link_to "Delete",article_path(a),method: :Delete, data:{confirm: "are you sure?!"},class:"btn btn-outline-danger" %>
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words(a.created_at) %> ago,
                        Edited <%= time_ago_in_words(a.updated_at) %> ago</small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
    <% if @art.errors.any? %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <h4 class="alert-heading">The following errors :</h4>
            <ul>
            <% @art.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <%end%>
            </ul>
        </div>
    <% end %>
    
        
    <div class="row justify-content-center">
        <div class="col-10">
            <%= form_with(model: @art,class: "shadow p-3 mb-3 bg-info rounded",local: true) do |f| %>
                
                <div class="form-group row">
                    <%= f.label :title,class: "col-2 col-form-label" %>
                    <div class="col-10">
                        <%= f.text_field :title, class: "form-control shadow rounded",placeholder:"Title of article" %>      
                    </div>      
                </div>
                        
                <div class="form-group row ">
                    <%= f.label :description,class: "col-2 col-form-label" %>
                    <div class="col-10">
                        <%= f.text_area :description,rows: 10,class: "form-control shadow rounded",placeholder:"Description" %>      
                    </div>      
                </div>

                <div class="form-group row ">
                    <%= f.label :category,class: "col-2 col-form-label" %>
                    <div class="col-10">
                    <%= f.collection_select(:category_ids, Category.all, :id, :name,
                            {prompt: "Please Select categories(can be empty)"}, {multiple: true, size:3, class:"custom-select shadow rounded"}) %>
                    </div>      
                </div>

                <div class="form-group row justify-content-center">
                    <%=  f.submit class:"btn btn-outline-light btn-lg" %>
                </div>

            <% end %>
        </div>

        <%= link_to '[ cancel and back to article list ]',articles_path%>
    </div>
</div>

app/views/articles/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Update article</h1>
    <%= render 'form' %>

</div>

app/views/articles/index.html.erb
<div id="page-content">

    <h1 class="text-center mt-4">Articles listing page</h1>
    <div class="apple_pagination">
        <%= will_paginate @arts, :container => false %>
    </div>
    <%= render 'article' %>

    <div class="apple_pagination">
        <%= will_paginate @arts, :container => false %>
    </div>
</div>

app/views/articles/new.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Create new article</h1>
    <%= render 'form' %>

</div>

app/views/articles/show.html.erb
<div id="page-content">
<div class="container">
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center mb-5 bg-white rounded">
                    <div class="card-header font-italic">
                        by <%= @art.user.username %>
                        <%= link_to gravatar_for(@art.user), user_path(@art.user) %>
                        <% if @art.categories.any?  %>
                            <div class="mt-2"><%= render @art.categories %> </div>
                        <% end %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= @art.title %></h5>
                        <p class="card-text"><%= @art.description %></p>
                        <% if logged_in? && (@art.user == current_user || current_user.admin?) %>
                            <%= link_to "Edit",edit_article_path(@art),class:"btn btn-outline-info" %>
                            <%= link_to "Delete",article_path(@art),method: :Delete, data:{confirm: "are you sure?!"},class:"btn btn-outline-danger" %>
                        <% end %>
                        <%= link_to "Back", articles_path,class:"btn btn-outline-info"%>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words(@art.created_at) %> ago,
                        Edited <%= time_ago_in_words(@art.updated_at) %> ago</small>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class:"badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
<div class="container">
    <% if @category.errors.any? %>
        <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">The following errors :</h4>
            <ul>
            <% @category.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <%end%>
            </ul>
        </div>
    <% end %>
    
        
    <div class="row justify-content-center">
        <div class="col-10">
            <%= form_with(model: @category,class: "shadow p-3 mb-3 bg-info rounded",local: true) do |f| %>
                
                <div class="form-group row">
                    <%= f.label :name,"category name",class: "col-2 col-form-label" %>
                    <div class="col-10">
                        <%= f.text_field :name, class: "form-control shadow rounded",placeholder:"Enter name" %>      
                    </div>      
                </div>
                        
                
                <div class="form-group row justify-content-center">
                    <%= f.submit class:"btn btn-outline-light btn-lg" %>
                </div>

            <% end %>
        </div>

        <%= link_to '[ cancel and back to category list ]',categories_path%>
    </div>
</div>

app/views/categories/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Update category</h1>
    <div class="container">
        <%= render 'form' %>    
    </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>
<div class="container">
    <div class="apple_pagination">
        <%= will_paginate @cats, :container => false %>
    </div>
    <% @cats.each do |a| %>
        <div class="row justify-content-md-center">
            <div class="col-4 mt-4">
                <div class="card text-center mb-5 bg-white rounded">
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to a.name,category_path(a),class: "text-success" %></h5>
                        <p class="card-text"><%=  pluralize(a.articles.count, "article") %></p>    
                    </div>
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words(a.created_at) %> ago,
                        Edited <%= time_ago_in_words(a.updated_at) %> ago</small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
    <div class="apple_pagination">
        <%= will_paginate @cats, :container => false %>
    </div>
</div>

app/views/categories/new.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Create a new category</h1>
    <div class="container">
        <%= render 'form' %>    
    </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4"><%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
    <div class="text-center mt-4">
        <%= link_to "Edit category name", edit_category_path(@category), class:"btn btn-outline-info" %>
    </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<div class="apple_pagination">
    <%= will_paginate @arts, :container => false %>
</div>
<%= render 'articles/article' %>

<%= link_to "Back", categories_path,class:"btn btn-outline-info"%>

<div class="apple_pagination">
    <%= will_paginate @arts, :container => false %>
</div>

app/views/layouts/_messages.html.erb
<div class="contaner">
    <% flash.each do |name,msg| %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">            <%= msg %>
            <button type="button" class="close" data-dismiss="alert" arila-label="Close">
                <span area-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "ALPHA BLOG" , root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Bloggers", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Articles
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if logged_in? %>
                <%= link_to "Create new article", new_article_path,class:"dropdown-item" %>
              <% end %>
              <%= link_to "View articles", articles_path,class:"dropdown-item" %>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categories
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if logged_in?  && current_user.admin? %>
                <%= link_to "Create new category", new_category_path,class:"dropdown-item" %>
              <% end %>
              <%= link_to "View categories", categories_path,class:"dropdown-item" %>
            </div>
          </li>

          <% if logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <%= "(Admin)" if current_user.admin? %> <%=current_user.username %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "View your profile", user_path(current_user),class:"dropdown-item" %>
                <%= link_to "Edit your profile", edit_user_path(current_user),class:"dropdown-item" %>
                <%= link_to "Delete your profile", user_path(current_user),class:"dropdown-item text-danger", method: :delete, data: { confirm: "Are youu sure?"}%>
              </div>
            </li>

          <li class="nav-item">
            <%= link_to "Log out" ,logout_path, class: "nav-link", method: :delete %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Log in" ,login_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign up" ,signup_path, class: "nav-link" %>
          </li>
          <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>this is about page</h1>
<%= link_to 'article list',articles_path%> |
<%= link_to 'home',root_path%>

app/views/pages/home.html.erb
<div id="page-content">
    <div class="container" id="home-container">
        <div class="jumbotron text-center text-white">
            <h1 class="display-4 text-white">Alpha Blog</h1>
            <p class="lead">Hope, is dangerous thing.</p>
            <hr class="my-4">
            <p>do not take life too seriously you will never get out of it alive </p>
            <%= link_to "sign Up!", signup_path, class: "btn btn-success btn-lg" %>
        </div>
    </div>
</div>
<footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy; Website</small>
    </div>
</footer>

app/views/users/_form.html.erb
<div class="container">
    <% if @user.errors.any? %>
        <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">The following errors :</h4>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <%end%>
            </ul>
        </div>
    <% end %>
    
        
    <div class="row justify-content-center">
        <div class="col-10">
            <%= form_with(model: @user,class: "shadow p-3 mb-3 bg-info rounded",local: true) do |f| %>
                
                <div class="form-group row">
                    <%= f.label :username,class: "col-2 col-form-label" %>
                    <div class="col-10">
                        <%= f.text_field :username, class: "form-control shadow rounded",placeholder:"Enter username" %>      
                    </div>      
                </div>
                        
                <div class="form-group row ">
                    <%= f.label :email,class: "col-2 col-form-label" %>
                    <div class="col-10">
                        <%= f.email_field :email,class: "form-control shadow rounded",placeholder:"email" %>      
                    </div>      
                </div>

                <div class="form-group row ">
                    <%= f.label :password,class: "col-2 col-form-label" %>
                    <div class="col-10">
                        <%= f.password_field :password,class: "form-control shadow rounded",placeholder:"choose a password" %>      
                    </div>      
                </div>

                <div class="form-group row justify-content-center">
                    <%=  f.submit(@user.new_record? ? "sign up" : "update", class:"btn btn-outline-light btn-lg") %>
                </div>

            <% end %>
        </div>

        <%= link_to '[ cancel and back to article list ]',articles_path%>
    </div>
</div>

app/views/users/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Update your profile</h1>
    <%= render 'form' %>

</div>

app/views/users/index.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Bloggers</h1>
    <div class="apple_pagination">
        <%= will_paginate @users, :container => false %>
    </div>

    <div class="container">
    <% @users.each do |user| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center mb-5 bg-white rounded">
                    <div class="card-header font-italic">
                        <%= link_to user.username, user %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">
                        <%= link_to gravatar_for(user,size:150),user %>
                        </h5>
                        <p class="card-text"><%=  pluralize(user.articles.count, "article") %></p>
                        <%= link_to "View profile",user,class:"btn btn-outline-success" %>
                        <% if logged_in? %>
                            <% if user == current_user %>
                                <%= link_to "Edit Profile",edit_user_path(user),class:"btn btn-outline-info" %>
                            <% end %>
                            <% if current_user.admin? %>
                                <%= link_to "Delete profile", user_path(user),class:"btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
                            <% end %> 
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Joined <%= time_ago_in_words(user.created_at) %> ago,
                        Updated <%= time_ago_in_words(user.updated_at) %> ago</small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
    </div>

    <div class="apple_pagination">
        <%= will_paginate @users, :container => false %>
    </div>

</div>

app/views/users/new.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">sign up for blog</h1>
    <%= render 'form' %>

</div>

app/views/users/show.html.erb
<div id="page-content">
    <h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>
    <%= gravatar_for @user,size:200 %>

    <% if logged_in? && @user == current_user %>
        <div class="text-center mt-4">
            <%= link_to "Edit your profile", edit_user_path(@user), class:"btn btn-outline-info" %>
        </div>
    <% end %>

    <h3 class="text-center mt-4">Articles</h3>

    <div class="apple_pagination">
        <%= will_paginate @arts, :container => false %>
    </div>
    <%= render 'articles/article' %>

    <div class="apple_pagination">
        <%= will_paginate @arts, :container => false %>
    </div>

</div>